name = "postgresql_protocol"
version = "1.0.0"
description = "PostgreSQL protocol encoding and decoding"
licences = ["Apache-2.0"]
repository = { type = "github", user = "grodaus", repo = "postgresql_protocol" }
links = [{ title = "Website", href = "https://github.com/grodaus/postgresql_protocol" }]
dependencies = { gleam_stdlib = "~> 0.36", mug = "~> 1.0", prng = "~> 3.0"}
dev-dependencies = {showtime = "~> 0.3"}
